/* eslint-disable */
// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

import * as React       from "react";
import * as ReasonReact from "reason-react/src/reasonReact.js";

var component = ReasonReact.statelessComponent("Title");

function make(label, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("h1", undefined, label);
    });
  return newrecord;
}

export {
  component ,
  make      ,
  
}
/* component Not a pure module */
