// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

import * as ReasonReact from "reason-react/src/reasonReact.js";

var component = ReasonReact.statelessComponent("Page");

export {
  component ,
  
}
/* component Not a pure module */
