// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

import * as Block       from "bs-platform/lib/es6/block.js";
import * as Curry       from "bs-platform/lib/es6/curry.js";
import * as Title       from "../Title/Title.js";
import * as React       from "react";
import * as Pervasives  from "bs-platform/lib/es6/pervasives.js";
import * as ReasonReact from "reason-react/src/reasonReact.js";

var component = ReasonReact.reducerComponent("Article");

function handleClick(_, self) {
  Curry._2(self[/* reduce */3], (function () {
          return /* Tick */0;
        }), /* () */0);
  var countStr = Pervasives.string_of_int(self[/* state */4][/* count */0]);
  console.log("clicked: " + countStr);
  return /* () */0;
}

function getInc(size) {
  return (size << 1);
}

function make(title, body, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      return React.createElement("div", {
                  onClick: Curry._1(self[/* handle */0], handleClick)
                }, ReasonReact.element(/* None */0, /* None */0, Title.make(title, /* array */[])), React.createElement("b", {
                      onClick: Curry._1(self[/* reduce */3], (function () {
                              return /* BodyClick */1;
                            }))
                    }, body));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* count */0];
    });
  newrecord[/* reducer */12] = (function (action, state) {
      if (action !== 0) {
        return /* UpdateWithSideEffects */Block.__(3, [
                  state,
                  (function () {
                      console.log("body clicked!");
                      return /* () */0;
                    })
                ]);
      } else {
        return /* Update */Block.__(0, [/* record */[/* count */state[/* count */0] + 2 | 0]]);
      }
    });
  return newrecord;
}

var jsComponent = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.title, jsProps.body, /* array */[]);
      }));

export {
  component   ,
  handleClick ,
  getInc      ,
  make        ,
  jsComponent ,
  
}
/* component Not a pure module */
