/* eslint-disable */
// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

import * as Title       from "../Title/Title.js";
import * as React       from "react";
import * as ReasonReact from "reason-react/src/reasonReact.js";

var component = ReasonReact.statelessComponent("Article");

function make(title, body, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var res = title + body;
      return React.createElement("div", undefined, ReasonReact.element(/* None */0, /* None */0, Title.make(title, /* array */[])), React.createElement("b", undefined, res));
    });
  return newrecord;
}

var jsComponent = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
        return make(jsProps.title, jsProps.body, /* array */[]);
      }));

export {
  component   ,
  make        ,
  jsComponent ,
  
}
/* component Not a pure module */
