// Generated by BUCKLESCRIPT VERSION 1.9.3, PLEASE EDIT WITH CARE
'use strict';

import * as $$String   from "bs-platform/lib/es6/string.js";
import * as Pervasives from "bs-platform/lib/es6/pervasives.js";

console.log("Hello there!");

function print() {
  console.log("Hey you!");
  return /* () */0;
}

function format(d, formatStr) {
  var day = d.getDay();
  var month = d.getMonth();
  var year = d.getFullYear();
  var ret = [""];
  $$String.iter((function (ch) {
          var exit = 0;
          exit = ch >= 90 ? (
              ch !== 100 ? (
                  ch !== 109 ? (
                      ch !== 121 ? 1 : 2
                    ) : 3
                ) : 4
            ) : (
              ch !== 68 ? (
                  ch !== 77 ? (
                      ch >= 89 ? 2 : 1
                    ) : 3
                ) : 4
            );
          switch (exit) {
            case 1 : 
                ret[0] = ret[0] + $$String.make(1, ch);
                return /* () */0;
            case 2 : 
                ret[0] = ret[0] + Pervasives.string_of_float(year);
                return /* () */0;
            case 3 : 
                ret[0] = ret[0] + Pervasives.string_of_float(month);
                return /* () */0;
            case 4 : 
                ret[0] = ret[0] + Pervasives.string_of_float(day);
                return /* () */0;
            
          }
        }), formatStr);
  return ret[0];
}

function format2(d, formatStr) {
  var day = d.getDate();
  var month = d.getMonth() + 1 | 0;
  var year = d.getFullYear();
  var ret = [""];
  $$String.iter((function (ch) {
          var exit = 0;
          exit = ch >= 90 ? (
              ch !== 100 ? (
                  ch !== 109 ? (
                      ch !== 121 ? 1 : 2
                    ) : 3
                ) : 4
            ) : (
              ch !== 68 ? (
                  ch !== 77 ? (
                      ch >= 89 ? 2 : 1
                    ) : 3
                ) : 4
            );
          switch (exit) {
            case 1 : 
                ret[0] = ret[0] + $$String.make(1, ch);
                return /* () */0;
            case 2 : 
                ret[0] = ret[0] + Pervasives.string_of_int(year);
                return /* () */0;
            case 3 : 
                var match = +(month < 10);
                ret[0] = ret[0] + (
                  match !== 0 ? "0" + Pervasives.string_of_int(month) : Pervasives.string_of_int(month)
                );
                return /* () */0;
            case 4 : 
                var match$1 = +(day < 10);
                ret[0] = ret[0] + (
                  match$1 !== 0 ? "0" + Pervasives.string_of_int(day) : Pervasives.string_of_int(day)
                );
                return /* () */0;
            
          }
        }), formatStr);
  return ret[0];
}

export {
  print   ,
  format  ,
  format2 ,
  
}
/*  Not a pure module */
